# This is a basic workflow to help you get started with Actions

name: Deploy Vue

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ENVIRONMENT: 'prod'
  EC2_USER: 'ec2-user'
  EC2_HOST: 'ec2-3-115-214-155.ap-northeast-1.compute.amazonaws.com'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup Node 
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: install can-npm-publish and dependencies and build
        run: |
          npm install can-npm-publish
          npm ci
          npm run build:prod

      - name: Scp ec2 copy vue modules
        env:
          PRIVATE_KEY: ${{ secrets.AWS_APPSRV1_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          echo "===== scp vue module ====="
          scp -o StrictHostKeyChecking=no -i private_key -r ./dist/ ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:/home/${{ env.EC2_USER }}/index

      - name: Ssh ec2 deploy vue module
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_APPSRV1_PRIVATE_KEY }}
          username: ${{ env.EC2_USER }}
          host: ${{ env.EC2_HOST }}
          script: |
            echo "===== deploy vue module ====="
            sudo cp -rf /home/${{ env.EC2_USER }}/index/dist/* /usr/share/nginx/html/demo/
